[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
whitespace-sifter = { path = ".." }
# collapse = "0.1.2"
criterion = "0.5.1"
# fast_whitespace_collapse = "0.1.0"

[[bench]]
name = "bench"
harness = false
